### ISSUE TITLE
Unraid Install - Error

### ISSUE THREAD

**Issue by Hawkins1212** [engels74/tgraph-bot-source#22]
A bit at a loss.  Fresh install of T Graphs (for unraid).  Set up the Bot and linked to Tautilli docker.  I am not getting any output in discord.

The below are the errors I see in the logs:

2024-08-27 00:03:28,848 - ERROR - Error in update_and_post_graphs: 'series'
2024-08-27 00:03:28,848 - INFO - Error during startup: 'series'
2024-08-27 00:03:28,848 - ERROR - An error occurred in on_ready: 'series'
2024-08-27 00:04:02,484 - ERROR - Error in update_and_post_graphs: 'series'
2024-08-27 00:04:02,484 - INFO - Error in /update_graphs command: 'series'

Any idea on troubleshooting steps for this?

**Comment by engels74** [comment]
Can you post a "redacted" version of your config.yml? Like redacting the API key and changing the URL to something bogus :). Like
`http://example.com/api/v2 ` or whatever

**Comment by Hawkins1212** [comment]
# config/config.yml.sample
TAUTULLI_API_KEY: [MY API WAS HERE]
TAUTULLI_URL: http://UNRAIDIP:8181/api/v2
DISCORD_TOKEN: [MY TOKEN WAS HERE]
CHANNEL_ID: [MY CHANNEL IP WAS HERE]
UPDATE_DAYS: 1
KEEP_DAYS: 7
TIME_RANGE_DAYS: 30
LANGUAGE: en

# Graph options
CENSOR_USERNAMES: true
ENABLE_DAILY_PLAY_COUNT: true
ENABLE_PLAY_COUNT_BY_DAYOFWEEK: true
ENABLE_PLAY_COUNT_BY_HOUROFDAY: true
ENABLE_TOP_10_PLATFORMS: true
ENABLE_TOP_10_USERS: true
ENABLE_PLAY_COUNT_BY_MONTH: true

# Graph colors
TV_COLOR: "#1f77b4"
MOVIE_COLOR: "#ff7f0e"
ANNOTATION_COLOR: "#ff0000"

# Annotation options
ANNOTATE_DAILY_PLAY_COUNT: true
ANNOTATE_PLAY_COUNT_BY_DAYOFWEEK: true
ANNOTATE_PLAY_COUNT_BY_HOUROFDAY: true
ANNOTATE_TOP_10_PLATFORMS: true
ANNOTATE_TOP_10_USERS: true
ANNOTATE_PLAY_COUNT_BY_MONTH: true

# My Stats command options
MY_STATS_COOLDOWN_MINUTES: 5
MY_STATS_GLOBAL_COOLDOWN_SECONDS: 60

**Comment by Hawkins1212** [comment]
Is the issue here:  TAUTULLI_URL: http://UNRAIDIP:8181/api/v2     When I swap to my ip address and input into my browser bar, Firefox spits out the following:
`<html><body>

result | "error"
-- | --
message | "Parameter apikey is required"
data | {}


</body>
</html>`

**Comment by engels74** [comment]
Looks right enough. You can test the API key and connection to Tautulli by using this CURL command:

```bash
curl -X GET "http://your.ip.here:8181/api/v2?apikey=YOUR_API_KEY&cmd=arnold"
```

This should return a quote from a random Arnold Schwarzenegger movie, like so:

```
curl -X GET "http://my.ip.here:8181/api/v2?apikey=386xxxxxxx194952xxx8e71d53529d&cmd=arnold"
{"response": {"result": "success", "message": null, "data": "Do it!"}}
```

**Comment by Hawkins1212** [comment]
Thanks for this.  I got an error that my API key was invalid.  I refreshed my Taut. API and updated the config file and now it woks!

**Comment by engels74** [comment]
Great! Glad it works :)
