### ISSUE TITLE
403 forbidden errors

### ISSUE THREAD

**Issue by jl94x4** [engels74/tgraph-bot-source#25]
`2024-09-08 23:54:11,246 - INFO - Command permissions checked successfully.
2024-09-08 23:54:11,247 - INFO - Updating and posting graphs on bot startup...
2024-09-08 23:54:11,247 - INFO - Manual graph update started.
2024-09-08 23:54:11,451 - INFO - Error during startup: 403 Forbidden (error code: 50001): Missing Access
2024-09-08 23:54:11,451 - ERROR - An error occurred in on_ready: 403 Forbidden (error code: 50001): Missing Access`

I'm getting this after setting up the config and starting it. What could be missing?

**Comment by jl94x4** [comment]
Managed to fix the above, however now getting this;

`2024-09-08 23:57:30,893 - ERROR - Error in update_and_post_graphs: Expecting value: line 2 column 1 (char 1)
2024-09-08 23:57:30,893 - INFO - Error during startup: Expecting value: line 2 column 1 (char 1)
2024-09-08 23:57:30,894 - ERROR - An error occurred in on_ready: Expecting value: line 2 column 1 (char 1)`

**Comment by engels74** [comment]
> Managed to fix the above, however now getting this;
> 
> ```2024-09-08 23:57:30,893 - ERROR - Error in update_and_post_graphs: Expecting value: line 2 column 1 (char 1)
> 2024-09-08 23:57:30,893 - INFO - Error during startup: Expecting value: line 2 column 1 (char 1)
> 2024-09-08 23:57:30,894 - ERROR - An error occurred in on_ready: Expecting value: line 2 column 1 (char 1)``

Can you post a "redacted" version of your config.yml? Like redacting the API key and changing the URL to something bogus :). Like
http://example.com/api/v2 or whatever

Also you can test the API key and connection to Tautulli by using this CURL command:

```bash
curl -X GET "http://your.ip.here:8181/api/v2?apikey=YOUR_API_KEY&cmd=arnold"
```

This should return a quote from a random Arnold Schwarzenegger movie, like so:

```
curl -X GET "http://my.ip.here:8181/api/v2?apikey=386xxxxxxx194952xxx8e71d53529d&cmd=arnold"
{"response": {"result": "success", "message": null, "data": "Do it!"}}
```:

**Comment by engels74** [comment]
Closing as its stale, no answer for weeks.

If you still need help, I've moved issues to the other repo:
https://github.com/engels74/tgraph-bot/issues

Kind regards,
engels74
